hikari-crescent/hikari-crescent

- crescent/commands/decorators.py
- crescent/commands/groups.py
- crescent/internal/app_command.py
- crescent/internal/registry.py
- rework groups to use object
- add hooks
Groups are now stored as the object instead of a `str`. I also removed the `group` and `sub_group` params in the `@crescent.command` decorator so now you can only use `@group.child` and `@sub_group.child`
> :sparkles: group hooks and description

- crescent/commands/errors.py
- crescent/commands/hooks.py
- crescent/context.py
- crescent/internal/handle_resp.py
- crescent/typedefs.py
- examples/error_handling/basic.py
- examples/hooks/group_hooks.py
- examples/hooks/hooks.py
Fixes #37. Fixes #45 
Added the following options to `Context`:
- options
- command
- group
- sub_group
- command_type
Removed the `options` kwarg from error and hook callbacks. They can use `ctx.options` instead.
Removed the `options` kwarg from `HookResult`. The can modify `ctx.options` directly instead.
I know you said you wanted them to not be able to modify ctx.options, but doing this adds overhead and complexity, both for us and for anyone using the lib. I think that if someone wants to modify options inside a hook, they should be allowed to do it directly. It doesn't have to be publicly supported.
I also fixed the `hook` decorator. Apparently that wasn't typehinted right, so I wasn't able to find it earlier when I moved `MetaStruct.interaction_hooks` to `AppCommandMeta.hooks`.
> ✨ Ctx `options`, `command`, `group`, `sub_group`, `command_type`

- crescent/bot.py
- crescent/internal/handle_resp.py
- examples/error_handling/basic.py
Fixes #60 
I went with  f"Unhandled exception occured in the command {ctx.command}:"
> :sparkles: Add catch-all error handler

- .gitattributes
It doesn't matter how docs merge since they will always be generated corrected by CI. This should remove annoying merge conflicts.
> :technologist: make merging docs merge correctly

- crescent/errors.py
- crescent/event.py
- crescent/exceptions.py
- crescent/internal/meta_struct.py
- crescent/internal/registry.py
- crescent/plugin.py
- crescent/typedefs.py
- examples/plugins/example.py
- examples/plugins/folder/another_plugin.py
- examples/plugins/plugin.py
- tests/crescent/plugins/hook_plugin.py
- tests/crescent/plugins/plugin.py
- tests/crescent/plugins/test_plugins.py
- tests/test_bot/test_plugin.py
Introduces a breaking change `crescent.catch_command` and other catch decorators can no longer be stacked. Not a huge issue imo since this shouldn't have been done anyway.
> :sparkles: Add plugin load and unload hook

- README.md
- crescent/internal/handle_resp.py
- tests/crescent/internal/test_extract_value.py
Fix bug where autocomplete did not work properly when a role was the in the same command as an option with autocomplete.
For example, this now works.
```py
async def autocomplete(ctx: crescent.Context, option: hikari.AutocompleteInteractionOption):
return [hikari.CommandChoice(name="1234", value="1234")]
@bot.include
@crescent.command
class autocomplete_test:
role = crescent.option(hikari.Role)
say = crescent.option(str, autocomplete=autocomplete)
async def callback(self, ctx: crescent.Context):
pass
```
Now a `Snowflake` object is passed instead of the user.
> :bug: Autocomplete now works properly when roles are an option in the command.

- crescent/plugin.py
Saw this in the Discord server: Pluin => Plugin
> Correct typo in deprecation message

- crescent/internal/app_command.py
- crescent/internal/registry.py
- tests/crescent/commands/test_command_function.py
- tests/crescent/commands/test_defaults.py
- tests/crescent/commands/test_option_types.py
- tests/crescent/internal/test_registry.py
I hope I didn't miss anything...
@Lunarmagpie also I don't know how the prefix command naming works, is having it app_command acceptable here?
> Rename `AppCommandMeta.app` property to `app_command`

- crescent/commands/decorators.py
- crescent/internal/app_command.py
- crescent/internal/registry.py
- crescent/plugin.py
- examples/hooks/plugin_hooks.py
- tests/crescent/hooks/test_hook_order.py
- tests/crescent/internal/test_registry.py
- tests/test_bot/test_bot.py
Removes plugin names, add_plugin, and the command deprecated kwarg.
Next release will be `0.3.0` so this is a good time to do this.
> :fire: Remove deprecated features

- crescent/__init__.py
- crescent/bot.py
- crescent/context.py
- crescent/context/__init__.py
- crescent/context/autocomplete_context.py
- crescent/context/base_context.py
- crescent/context/context.py
- crescent/internal/handle_resp.py
- crescent/typedefs.py
- examples/basic/autocomplete.py
- examples/error_handling/basic.py
I spent a long time thinking about the implementation and this was the best I could think of
Breaking change. Requires the user to change the `crescent.Context` typehint to `crescent. AutocompleteContext` for autocomplete commands.
This system can easily be extended to allow users to use custom context types. (I think this system will add more complexity then its worth though, just want to keep the option open)
> :sparkles: Add autocomplete context

- crescent/exceptions.py
- crescent/internal/app_command.py
- crescent/internal/registry.py
- crescent/typedefs.py
This will stop `crescent` from breaking whenever there is a change to builders. Specific types of builders were not type safe anyway so I dont think this PR removes any type safety.
> :bug: Remove inheritance from hikari builders

- crescent/internal/registry.py
This PR adds a new method `purge_commands` onto `CommandHandler`.
By default it will purge all global commands and all commands in `tracked_guilds` with kwargs to alter that behavior.
> :sparkles: Add purge_commands method to CommandHandler

- .github/workflows/publish.yml
The type hints look better in the docs because they can be parsed by pdoc
> :green_heart: Make pdoc build with python3.10

- crescent/internal/handle_resp.py
The fix is to have a whitelist instead of a blacklist.
All tests are passing, so this shouldn't break *much*.
> fix crescent choking on modal interactions

- README.md
- crescent/__init__.py
- crescent/commands/args.py
- crescent/commands/decorators.py
- crescent/commands/options.py
- crescent/commands/signature.py
- crescent/context/base_context.py
- crescent/internal/app_command.py
- crescent/internal/handle_resp.py
- crescent/internal/registry.py
- crescent/locale.py
- examples/locales/basic.py
- examples/locales/builder.py
- tests/crescent/commands/test_argparse.py
- tests/crescent/commands/test_build.py
- tests/crescent/ctx/test_autocomplete_ctx.py
- tests/crescent/ctx/test_ctx.py
- tests/crescent/plugins/test_plugins.py
- tests/crescent/test_locale.py
- tests/utils/__init__.py
- tests/utils/locale.py
This PR adds `crescent.LocaleBuilder` which can be used to to write locale implementations. It is done like this so `crescent` is opinionated minimally in this area.
The `locale` field is also added to `crescent.BaseContext`.
> :sparkles: Add Locale Implementation

- crescent/ext/cooldowns/__init__.py
- crescent/ext/tasks/cron.py
- noxfile.py
- pyproject.toml
This lowers the amount of dependencies required to run crescent.
> Add dependency groups for ext

- crescent/__init__.py
- crescent/commands/groups.py
- crescent/exceptions.py
- crescent/internal/registry.py
- tests/crescent/commands/test_permissions.py
Permissions v2 should be declared in the top level of the command. This PR adds that.
> :bug: Move permissions to `crescent.Group`

- crescent/ext/cooldowns/__init__.py
- examples/ext/cooldowns/basic.py
- examples/ext/cooldowns/custom_bucket.py
- pyproject.toml
This PR switches to floodgate for rate limiting. Change is made because pycooldown is no longer supported.
Breaking changes
- `datetime.timedelta` expected for cooldown duration
- `datetime.timedelta` returned for time left after being rate limited
> :boom: Use floodgate for ratelimiting

- pyproject.toml
This will prevent future hikari versions, e.g. dev121, from introducing breaking changes that cause this crescent version to break.
> set the hikari version to ==dev120

- crescent/context/autocomplete_context.py
- crescent/context/context.py
- crescent/ext/tasks/loop.py
- crescent/internal/handle_resp.py
Add a `set_interval` function to change the time a loop waits before running the next task.
I ignored some type errors since a pyright update now detects them. It would be a kinda big refactor to fix these.
> Loop set interval function

- crescent/context/context.py
Changed "ephermial" to "ephemeral"
> Fix typo of ephemeral
