hikari-crescent/hikari-crescent

crescent/bot.py

This is my fault, I changed the method name on the class but not on Bot.

plugin._setup not plugin.setup

---

crescent/bot.py
crescent/commands/decorators.py
crescent/internal/app_command.py
crescent/internal/registry.py

- :bug: plugin._setup not plugin.setup (#4)
- :bug: Fix annotations when theres an annotations import (#5)
- commands now register when argument count changes from 0-1+ or 1+ to 0
- added docs
- fix guilds sometimes not being in cache
- fix guild undefined

:bug: fix command registration

---

.flake8
.pre-commit-config.yaml
crescent/__init__.py
crescent/bot.py
crescent/commands/__init__.py
crescent/commands/decorators.py
crescent/commands/options.py
crescent/internal/registry.py
crescent/typedefs.py
examples/api.py
examples/example.py
examples/plugin.py
poetry.lock
pyproject.toml

Ignore the extra commits "Merges and plugin.setup -> plugin._setup", I think that's just a side effect of squash merging.

Class Commands, Snowflake -> Snowflakeish

---

crescent/bot.py
crescent/commands/decorators.py
crescent/commands/groups.py
crescent/event.py
examples/example.py

The commits kinda give a good overview of what changed.

Typhints, Group.child(), guilds -> tracked_guilds, fix class commands in bot, update example

---

crescent/__init__.py
crescent/bot.py
crescent/event.py
crescent/exceptions.py
crescent/internal/app_command.py
crescent/internal/handle_resp.py
crescent/internal/registry.py
poetry.lock
pyproject.toml

- add codespell and gateway bot docs
- add warnings for non-async functions
- :bug: fix global commands
- remove codespell

:bug: fix global commands and raise exceptions

---

.flake8
.isort.cfg
.mypy.ini
crescent/commands/decorators.py
crescent/commands/options.py
crescent/context.py
crescent/event.py
crescent/internal/app_command.py
crescent/internal/handle_resp.py
crescent/internal/registry.py
crescent/mentionable.py
crescent/utils/iterate_vars.py
examples/example.py
pyproject.toml

I also changed some mypy settings
```
warn_return_any = true
warn_redundant_casts = true
```

:truck: move setting to pyproject.toml

---

crescent/context.py

:art: Fix code duplication in Context.reply

---

crescent/commands/args.py

Use *args for Choices and ChannelTypes

---

.gitignore
crescent/commands/decorators.py
crescent/commands/options.py
examples/example.py

✨ Option name param

---

crescent/commands/decorators.py

:sparkles: Optional typehint

---

.github/workflows/publish.yml

Not sure if I used the right emoji lol

🧑‍💻 Create publish.yml

---

crescent/__init__.py
crescent/commands/decorators.py
crescent/commands/groups.py
crescent/internal/app_command.py
crescent/internal/handle_resp.py
crescent/internal/registry.py
crescent/typedefs.py

:art: `CommandCallback` -> `CommandCallbackT`

---

README.md
pyproject.toml

- start readme
- Update README.md
- add readme to pyproject
- update readme
- remove useless whitespace
- fix dependency

:bug: fix attrs dependency

---

crescent/banner.txt
pyproject.toml

:tada: 0.1.0-beta.1

---

crescent/context.py

:technologist: add ensure_message

---

.github/workflows/mypy.yml
crescent/internal/app_command.py

Despite the branch name, I didn't bother with Nox. A simple github action should be good enough for now.

:construction_worker: Add basic github action for mypy

---

crescent/internal/handle_resp.py

:bug: fix options in sub_group

---

.github/workflows/pdoc.yml

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters

Only build docs on push to main

---

crescent/context.py
crescent/internal/handle_resp.py

Removes RestAndCacheAware class
closes #101

Type `Context.app` as `crescent.Bot`

---

crescent/commands/signature.py
tests/crescent/commands/test_argparse.py
tests/utils/__init__.py
tests/utils/arrays.py

:bug: Allow Union[Channel Types] as typehint

---

.codeclimate.yml
README.md
examples/basic/basic.py
examples/hooks/hooks.py

i couldn't find a good place to sneak in @CircuitSacul :skull:

:memo: README and small doc updates

---

crescent/ext/cooldowns/__init__.py

Improve default callback

---

README.md
pyproject.toml

Change crescent's description to "A command handler for Hikari that keeps your project neat and tidy."

:memo: Update description

---

README.md

I hope you don't mind another PR lol.

Address a few typos in README file

---

crescent/internal/app_command.py
poetry.lock
pyproject.toml

who makes a random method an abstract method smh

:arrow_up: Support dev109

---

.github/dependabot.yml

:wrench: Add dependabot

---

crescent/plugin.py
tests/crescent/plugins/test_plugins.py

:sparkles: Add app attribute to plugins

---

README.md

:memo: Add hikari-ext-kebabify to README

---

crescent/plugin.py
tests/crescent/plugins/test_plugins.py

:technologist: Add warning if no plugins are loaded with load_folder

---

crescent/plugin.py
tests/crescent/plugins/test_plugins.py

:bug: Make refresh kwarg work for load_folder

---

crescent/commands/signature.py
crescent/context/utils.py
crescent/utils/__init__.py
crescent/utils/any_issubclass.py
tests/crescent/utils/test_any_issubclass.py

Um, not really sure why this fixes it but its correct so whatever ig.

:bug: Fix bug when using Annotated and no ctx typehint

---

crescent/internal/handle_resp.py
tests/crescent/internal/test_extract_value.py

- fix the bug
- add tests
- formatting

Fix attachment and channel deserialization

---

crescent/context/autocomplete_context.py
crescent/internal/handle_resp.py
examples/basic/autocomplete.py
examples/basic/function_commands.py
tests/crescent/ctx/test_autocomplete_ctx.py
tests/crescent/internal/test_extract_value.py

:sparkles: Add `fetch_options` to autocomplete

---

pyproject.toml

:arrow_up: bump hikari to 2.0.0.dev111

---

crescent/commands/args.py
crescent/commands/options.py
crescent/commands/signature.py
tests/crescent/commands/test_argparse.py

:sparkles: Add min and max string length

---

.github/workflows/pytest.yml
pyproject.toml

:arrow_up: Support python 3.11 

---

.github/workflows/pytest.yml
crescent/errors.py
crescent/utils/gather_iter.py
examples/locales/basic.py
pyproject.toml
tests/crescent/commands/test_permissions.py
tests/crescent/plugins/test_plugins.py

needs to be done so I can test other PRs without things failing

bump hikari to dev115

---

crescent/commands/decorators.py
crescent/internal/app_command.py
crescent/internal/registry.py
tests/crescent/commands/test_defaults.py

Add nsfw kwarg

---

crescent/client.py
crescent/plugin.py
examples/custom_contexts/compatible_context.py
examples/hooks/hooks.py
examples/hooks/plugin_hooks.py
examples/plugins/example.py
examples/plugins/folder/another_plugin.py
examples/plugins/plugin.py
tests/crescent/plugins/test_plugins.py
tests/utils/mock_client.py

This is an example of how the system will work https://github.com/Lunarmagpie/crescent-template/tree/model-mockup
I think the cost of this change is extremely low so I want to support it.

Support model object to store globals 

---

README.md

- update links to point to new locations

Update links to point to new locations

---

crescent/client.py
crescent/ext/tasks/task.py
crescent/utils/__init__.py
crescent/utils/tasks.py
pyproject.toml

Fix Dangling Tasks

---

crescent/errors.py
crescent/internal/registry.py

- allow error handlers to catch subclasses of an error
- update docs

Catch all subclasses of exceptions in error handlers

---

pyproject.toml

dependabot decided to
So this supersedes #294

update a bunch of dev dependencies

---

README.md

Add autocomplete example to readme

---

README.md

The template will help people understand crescent faster.

:memo: Add template to README

---

crescent/context/context.py
crescent/internal/handle_resp.py
pyproject.toml

- upgrade hikari to dev-122
- upgrade python to <3.13
- fix codespell errors that popped up out of nowhere

⬆️ upgrade hikari to dev-122

---

.github/workflows/publish.yml
.gitignore
docs/build.sh
docs/index.md
mkdocs.yml
noxfile.py
pyproject.toml

Move to mkdocs

---

README.md

don't forget to add the git emoji when merging lol

Remove function command from autocomplete info

---

docs/guides/plugins.md

:memo: Docs reword

---

crescent/internal/app_command.py
crescent/internal/registry.py
crescent/typedefs.py
tests/crescent/commands/test_build.py
tests/crescent/commands/test_command_function.py
tests/crescent/internal/test_compare_commands.py
tests/crescent/internal/test_registry.py

title
Tests must still be written.

:bug: Compare commands before posting

---

crescent/internal/app_command.py
tests/crescent/commands/test_build.py

fix: remove permission field if none set

---

crescent/commands/decorators.py
crescent/commands/groups.py
crescent/internal/app_command.py
crescent/internal/registry.py
tests/crescent/commands/test_defaults.py
tests/crescent/internal/test_compare_commands.py
tests/test_bot/test_bot.py

- **changes**
- **make changes**

Add Context Option
